# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:5.6.13
#RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install x-pack
# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
