FROM redis
COPY ./config/redis.conf /usr/local/etc/redis/config/redis.conf
CMD [ "redis-server", "/usr/local/etc/redis/config/redis.conf" ]
#EXPOSE "6378"
#CMD ["redis-server","--port","6378", "--bind", "172.17.0.1"]

